### PR TITLE
Cleanup CI (copy from expo)

### PR DESCRIPTION
**Pull request by maennchen**

### CODE REVIEW

**Comment by maennchen** [comment]
@whatyouhide I reconfigured the `main` branch rules so that the PR passes.

We seem to have a tiny issue in the error messages on elixir `main` where charlists are printed unsing the `~c` sigil instead of just single quotes.

**Comment by whatyouhide** [comment]
@maennchen let's remove testing on Elixir `main`, we don't get much benefit in such a tiny library anyways 👍

**Comment by maennchen** [comment]
@whatyouhide I personally think that the error we got right here is the perfect example why testing on main is a good idea.

Main is currently allowed to fail and should not block work. (Not set as a required check to pass for PR)

**Comment by whatyouhide** [comment]
> the error we got right here is the perfect example why testing on main is a good idea

@maennchen what would the action to take be in a case such as this one? We can't change to `~c` anyways, so knowing there's a failure is not really helpful in my opinion, no?

**Comment by maennchen** [comment]
@whatyouhide I think it is worth it for us to know in advance, that an upcomming elixi rchange is breaking code / tests.

In that specific instance the simplest solution was to use a binary instead: https://github.com/elixir-gettext/expo_plural_forms/pull/31/files#diff-85eb63af0a6128f55783dc634a7c546e65a22f4b919447998962cc8013427ac3R43

**Pull request merged**
