### PR TITLE
Remove ExpoPluralForms.compile_index/1

### PR DESCRIPTION
**Pull request by whatyouhide**
I think we can YAGNI this and go with evaluation only for now. This removes quite a bit of code and complexity. Thoughts @maennchen?

### CODE REVIEW

**Comment by maennchen** [comment]
@whatyouhide The idea was to use this one here:

https://github.com/elixir-gettext/gettext/pull/343/files#diff-08a210699de708eacba0bb488d5aaf7a597084db86d0d64ced68fde88a3aa982R159

I did however not do any benchmarking. Therefore I'm not sure how big the difference is with more complicated cases like arabic.

**Comment by maennchen** [comment]
Performance Comparison:

```elixir
Mix.install([{:benchee, "~> 1.1"}, {:expo_plural_forms, path: "."}])

{:ok, arabic} = ExpoPluralForms.Known.plural_form("ar")

defmodule Arabic do
  def index(n), do: unquote(ExpoPluralForms.compile_index(arabic))
end

Benchee.run(
  %{
    "precompiled" => fn ->
      Arabic.index(17)
    end,
    "without" => fn ->
      ExpoPluralForms.index(arabic, 17)
    end
  },
  time: 10,
  memory_time: 2
)
```

```
Operating System: Linux
CPU Information: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
Number of Available Cores: 8
Available memory: 46.77 GB
Elixir 1.14.2
Erlang 25.2

Benchmark suite executing with the following configuration:
warmup: 2 s
time: 10 s
memory time: 2 s
reduction time: 0 ns
parallel: 1
inputs: none specified
Estimated total run time: 28 s

Benchmarking precompiled ...
Benchmarking without ...

Name                  ips        average  deviation         median         99th %
precompiled       12.80 M       78.13 ns ±11238.24%          71 ns         122 ns
without            4.96 M      201.66 ns ±17907.47%         172 ns         349 ns

Comparison: 
precompiled       12.80 M
without            4.96 M - 2.58x slower +123.53 ns

Memory usage statistics:

Name           Memory usage
precompiled             0 B
without                 0 B - 1.00x memory usage +0 B

**All measurements for memory usage were the same**
```

Based on this, I would keep this for sure.

**Comment by whatyouhide** [comment]
Oh wow, based on that I want to 100% not have this 😀 We're talking nanoseconds, so it won't matter really. And having less code to maintain seems like a much bigger advantage.

**Comment by maennchen** [comment]
@whatyouhide I tend to agree.

I think it makes sense to remove it here and use a system similar to plug `int`, `call` to avoid parsing multiple times in https://github.com/elixir-gettext/gettext/pull/343

I'll approve this one and rethink the other PR.

**Review by maennchen — APPROVED** [review]

**Pull request merged**
